### ISSUE TITLE
After adding babel-plugin-import, prettier cannot parse "type modifiers on import(TS4.5 feature)"

### ISSUE THREAD

**Issue by mori5321** [avocadowastaken/babel-plugin-direct-import#117]
After I installed babel-plugin-import into my project, prettier(on pre-commit hook) starts to raise an parse error about **type modifiers on import**, which was implemented in TypeScript 4.5 & babel 7.16.0(https://github.com/babel/babel/pull/13802).

## The Error Logs
```
✖ prettier --write:
[error] packages/components/src/XXX.tsx: SyntaxError: ',' expected. (20:8)
[error]   19 | import {
[error] > 20 |   type XXXXType,
```

Does anyone have some clue to fix this?

**Comment by avocadowastaken** [comment]
Hey @mori5321 ! This error looks strange, since `prettier` uses `typescript-eslint` parser, not `babel`, can you reproduce it in the isolated project?

**Comment by mori5321** [comment]
@umidbekk 
Thank you for your reply! 

I found out it was my mistake. Other babel-plugin was unexpectedly left in my node_modules (though I thought I deleted). After I remove the plugin, the error disappear.  So it was not the effect of this library, and **I'll close this issue.**

By the way, I appreciate this awesome library you created. It saves me a lot of times. Thank you so much!

**Comment by mori5321** [comment]
Closed because this was invalid report of mine.
