### ISSUE TITLE
Dive into material-ui sub-modules

### ISSUE THREAD

**Issue by b1f6c1c4** [avocadowastaken/babel-plugin-direct-import#12]
Is it possible to compile
```js
import { Tab } from 'material-ui/Tabs';
```
into
```js
import Tab from 'material-ui/Tabs/Tab';
```
?

**Comment by avocadowastaken** [comment]
Hello @b1f6c1c4 !

No, this module parses only first `index.es.js` file and ignore all nested files.

Anyways `babel-plugin-direct-import` is officially [deprecated](https://github.com/umidbekkarimov/babel-plugin-direct-import/commit/1dea425a05bb7f501291b3e48fc2ae11611f33f7), and MUI has [side effects flag](https://github.com/mui-org/material-ui/blob/v1-beta/package.json#L207) so good luck with Webpack 4! :)
