### ISSUE TITLE
Allow missing dependencies

### ISSUE THREAD

**Issue by zvs001** [avocadowastaken/babel-plugin-direct-import#121]
When I apply configuration to project, which don't have some dependency from the list, it is crashing.
In example I didn't add `@mui/lab` to the project.

It would be useful to allow it.

Error:
```
Module build failed (from ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js):
AssertionError [ERR_ASSERTION]: failed to find entry file of '@mui/lab'.
    at Function.get (node_modules/babel-plugin-direct-import/lib/internal/NodeModule.js:48:14)
    at node_modules/babel-plugin-direct-import/lib/internal/PluginOptions.js:46:34
    at Array.map (<anonymous>)
    at Function.parse (node_modules/babel-plugin-direct-import/lib/internal/PluginOptions.js:37:17)

```

**Comment by avocadowastaken** [comment]
Hey @zvs001 ! Can you share your babel config?

**Comment by zvs001** [comment]
Hi @umidbekk 

Here is config file: https://github.com/zvs001/babel-config/blob/master/react/babel.json

Btw you can try to install by readme in root.
I use it as config to different projects, so not all of them require all defined libraries, and it creating this issue.

**Comment by avocadowastaken** [comment]
Oh, I see. But I don't think it's a good idea to ignore errors about missing explicitly provided modules.

You want to make reusable a config, maybe it's better to use `babel.config.js` file and scan `package.json` to exclude missing dependencies.

**Comment by zvs001** [comment]
I thought it would be useful to support by library. I think previously I didn't had such issues with `babel-plugin-transform-imports`.

But you suggestion also can work. Thank you.
