### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by ghost** [avocadowastaken/babel-plugin-direct-import#13]
Could you elaborate as to why the plugin is now discouraged from being used? Tree shaking in Webpack 4 does not affect material-ui@next because the latter still exports CommonJS modules. So, if someone is using CJS version, and not [`/es`](https://material-ui.com/guides/minimizing-bundle-size/#ecmascript) (which most people don't), would you recommend `babel-transform-imports` instead? Apparently this plugin is still suggested by libraries like [mdi-material-ui](https://github.com/TeamWertarbyte/mdi-material-ui/issues/9).

**Comment by avocadowastaken** [comment]
Hi @alexnez96!

I'm still using this plugin for `react-native` projects along with `babel-plugin-lodash` and `babel-plugin-date-fns`.

But in web projects backed up with webpack, rollup or parcel - there is an alternative.

In case of material-ui and many other libs that didn't optimized for es modules tree shaking `babel-plugin-direct-import` or `babel-transform-imports` will be useful, but still, it will be a workaround.
