### ISSUE TITLE
What about lodash and others?

### ISSUE THREAD

**Issue by mrchief** [avocadowastaken/babel-plugin-direct-import#2]
Is the plan to eventually support lodash and other such libs? 

While this is a neat idea, I don't want to end up having multiple import plugins for every few libs. Keeping track of who does what is just fragile and too much overhead than simply writing the imports in a modular way. 

Currently it seems I'd need this and `babel-transform-imports`  and `babel-plugin-lodash` if I'm using lodash, react and material-ui@next (which is a very common setup for many people).

I'd rather have a single plugin that supports all (which is what your tagline seems to imply) or simply write modular imports rather than remember who does what. 

Make sense?

**Comment by avocadowastaken** [comment]
Hello @mrchief!

Current plugin scans only index files with es6 modules, for example in [react-router](https://unpkg.com/react-router@4.1.2/es/index.js) or [material-ui](https://unpkg.com/material-ui@0.18.7/index.es.js), but [lodash](https://unpkg.com/lodash@4.17.4/lodash.js) has cjs requires.

I feel your frustration, currently I have to use `lodash`, `date-fns` and `direct-import` plugins.

P.S. Tree shaking should be a long term solution and plugins like this are just a short term workarounds.
