### ISSUE TITLE
Confused by new examples in ReadMe

### ISSUE THREAD

**Issue by jkhaui** [avocadowastaken/babel-plugin-direct-import#25]
Hi, 

I am trying to set this up with babel for a specific npm library. I am confused by the new example in the README and I'm not sure if I'm doing this right?

```
    [
      "babel-plugin-direct-import",
      {
        "modules": [
          "@appbaseio/reactivesearch"
        ]
      }
  ]
```

Whereas in the documentation for appbaseio, they have it written like this:

```
  [
          "direct-import",
          [
            "@appbaseio/reactivesearch",
            {
              "name": "@appbaseio/reactivesearch",
              "indexFile": "@appbaseio/reactivesearch/lib/index.es.js"
            }
          ]
        ]
    ]
```

Thanks for clarifying

**Comment by avocadowastaken** [comment]
Hello @jkhaui and thanks for the report. I add the [migration guide](https://github.com/umidbekkarimov/babel-plugin-direct-import#050-to-060) to make it easier to transfer.

This config should work for you. An index file (`@appbaseio/reactivesearch/lib/index.es.js`) will be automatically resolved from the package.json.

```json
{
  "plugins": [["direct-import", ["@appbaseio/reactivesearch"]]]
}
```

**Comment by jkhaui** [comment]
@umidbekkarimov Thank you very much for your quick reply. The problem is that this configuration is invalid as babel expects an object, but instead your snippet (as well as the others I've tried) have an array instead.

Any ideas>

**Comment by avocadowastaken** [comment]
@jkhaui oops, copied wrong example, try this one 

```json
{
  "plugins": [
    [
      "direct-import",
      {
        "modules": ["@appbaseio/reactivesearch"]
      }
    ]
  ]
}

```

**Comment by jkhaui** [comment]
Great thank you, that seems to work!
