### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by matuscongrady** [avocadowastaken/babel-plugin-direct-import#7]
Hello,

Babel 7 is behind the doors, and it comes with many nice improvements.
But it aswell comes with some deprecations. Babel 7 doesn't allow arrays as second argument to plugin.

.babelrc:
```javascript
presets: [
    ['direct-import', ['...options...']]
]
```
This `options` has to be an object, not array.
You can find out how babel-plugin-lodash dealt with this:
https://github.com/lodash/babel-plugin-lodash

Thanks!

**Comment by avocadowastaken** [comment]
Hello @mcongy!

Thanks for heads-ups! I'll take a look at it in weekends.

**Comment by avocadowastaken** [comment]
Published as `babel-plugin-direct-import@next`.
