### ISSUE TITLE
Not working for material-ui@next

### ISSUE THREAD

**Issue by Graham42** [avocadowastaken/babel-plugin-direct-import#8]
babel-plugin-direct-import version: `0.4.0`
material-ui version: `1.0.0-beta.18`

I've double and triple checked that my code is not importing the `List`,`Menu`, and `Popover` components but they're still showing up when I run `source-map-explorer` to investigate bundle size.

![image](https://user-images.githubusercontent.com/2476733/33082528-0482f868-ceab-11e7-98fa-29e3f2c4a564.png)

**Comment by avocadowastaken** [comment]
Hello @Graham42 !

This plugis was built for material-ui@next in first place. So it should work with zero-configuration.

Please check you dependency graph with [webpack analyze tool](https://github.com/webpack/webpack/issues/690).

**Comment by avocadowastaken** [comment]
Also, maybe it's worth to check with one of `source-map-explorer` [analogues ](https://medium.com/@joeclever/three-simple-ways-to-inspect-a-webpack-bundle-7f6a8fe7195d).

**Comment by Graham42** [comment]
I tried those 3 tools and they all reported the same result.

I've narrowed this down to the `TextField` component. I've created a minimal case you can verify for yourself if you like. https://github.com/Graham42/bug-babel-direct-import-material-ui-next
Just run 
```sh
npm run build
npm run stats
```

If you import just `Button` for example, the plugin works correctly. It's just once I have the `TextField` that it bundles a bunch extra.

**Comment by avocadowastaken** [comment]
Here my result:
![image](https://user-images.githubusercontent.com/4734297/33095801-b13fbeb2-cf26-11e7-9b7a-8fb3efb43eaf.png)

From this we can see that not all modules included, but only (I will skip obvious ones):
* ButtonBase
* List
* Modal
* Form
* Select
* Popover
* Menu
___
I checked `TextField` [dependencies](https://github.com/mui-org/material-ui/blob/v1-beta/src/TextField/TextField.js#L4-L10):
```javascript
import React from 'react';
import warning from 'warning';
import type { ChildrenArray, Node } from 'react';
import Input, { InputLabel } from '../Input';
import FormControl from '../Form/FormControl';
import FormHelperText from '../Form/FormHelperText';
import Select from '../Select/Select';
```
Now trail leads to `Select` component [dependencies](https://github.com/mui-org/material-ui/blob/v1-beta/src/Select/Select.js#L4-L10):
```javascript
import React from 'react';
import type { ChildrenArray, Element } from 'react';
import warning from 'warning';
import SelectInput from './SelectInput';
import withStyles from '../styles/withStyles';
import Input from '../Input'; // Import to enforce the CSS injection order
import { isMuiElement } from '../utils/reactHelpers';
```
And `SelectInput` [dependencies](https://github.com/mui-org/material-ui/blob/v1-beta/src/Select/SelectInput.js#L3-L10):
```javascript
import React from 'react';
import type { Element, Node } from 'react';
import classNames from 'classnames';
import keycode from 'keycode';
import warning from 'warning';
import Menu from '../Menu/Menu';
import { isDirty } from '../Input/Input';
import ArrowDropDownIcon from '../svg-icons/ArrowDropDown';
```
And finally `Menu` [dependencies](https://github.com/mui-org/material-ui/blob/v1-beta/src/Menu/Menu.js#L4-L11):
```javascript
import React from 'react';
import type { Node } from 'react';
import { findDOMNode } from 'react-dom';
import getScrollbarSize from 'dom-helpers/util/scrollbarSize';
import withStyles from '../styles/withStyles';
import Popover from '../Popover';
import MenuList from './MenuList';
import type { TransitionCallback } from '../internal/transition';
```
With `MenuList` [dependencies](https://github.com/mui-org/material-ui/blob/v1-beta/src/Menu/MenuList.js#L4-L11):
```javascript
import React from 'react';
import type { Node } from 'react';
import { findDOMNode } from 'react-dom';
import keycode from 'keycode';
import contains from 'dom-helpers/query/contains';
import activeElement from 'dom-helpers/activeElement';
import ownerDocument from 'dom-helpers/ownerDocument';
import List from '../List';
```
___

I wish this example will help you understand why you have unimported code in your app.

Have a nice hacking!

**Comment by Graham42** [comment]
That's unfortunate that components unrelated to my simple use case are getting pulled in. Thanks for your help. I've open https://github.com/mui-org/material-ui/issues/9262 to hopefully improve this.
