### ISSUE TITLE
Error when importing flow types

### ISSUE THREAD

**Issue by sarakusha** [avocadowastaken/babel-plugin-direct-import#9]
When using the Flow type definitions for react-router from `flow-typed/npm`, webpack builds fail with the following error message:
```javascript
Module build failed: Error: /Users/.../ToggleableMenuItem.js: babel-plugin-direct-import: react-router does not contain module "ContextRouter"
```
ToggleableMenuItem.js
`import type { ContextRouter } from 'react-router';`
[see same lodash issue](https://github.com/lodash/babel-plugin-lodash/issues/153)

**Comment by avocadowastaken** [comment]
Thanks @sarakusha ! Published in [0.5.0](https://github.com/umidbekkarimov/babel-plugin-direct-import/releases/tag/0.5.0).
